### ISSUE TITLE
Size limit on call result return value to view pure function

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#533]
### Description

There appears to be an issue(or internal constraint) on the length of the call result to `view`/`pure` functions. The limit appears to be 32*126=4032 bytes(~4KB). This is too low as some applications require reading a call result >1 MB.

### Steps to reproduce

1. Create `ReadData.sol` with the following contents:
```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity >=0.8.0;

contract ReadData {

    struct LotsOfData {
        uint number1;
        uint number2;
    }

    function getLotsOfData(
        uint24 count
    ) external pure returns (LotsOfData[] memory) {
        LotsOfData[] memory lotsOfData = new LotsOfData[](count);
        return lotsOfData;
    }

    struct NotLotsOfData {
        uint number;
    }

    function getNotLotsOfData(
        uint24 count
    ) external pure returns (NotLotsOfData[] memory) {
        NotLotsOfData[] memory notLotsOfData = new NotLotsOfData[](count);
        return notLotsOfData;
    }
}
```
2. Call `getLotsOfData` and `getNotLotsOfData` with `count` <=63 and <=126 respectively and observe the successful null call result
3. Repeat the same call but now with `count` >63 and >126 respectively and observe the call fails

### Hedera network

testnet

### Version

testnet@latest

**Comment by mshakeg** [comment]
The limit on the hedera local node seems to be 59392 bytes(~59KB) which is still too small.

**Comment by Ivo-Yankov** [comment]
There are 2 limiting factors for the result size - `gasLimit` and the transaction execution time. When increasing the `gasLimit` I managed to receive a result of >700 kb: 
```
    const tx = await contract.getLotsOfData(11175, {
      gasLimit: 15000000
    });
```
However it is possible that due to differences in hardware or OS the local node performs differently for you and you could be reaching the hardcoded maximum of 10s for transaction execution in the SDK. There is a [logged issue](https://github.com/hashgraph/hedera-sdk-js/issues/1276) to make that value configurable.

**Comment by Ivo-Yankov** [comment]
The issue is resolved in the latest release of the SDK - v2.18.6

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov , I don't see a pull request associated with this issue for the SDK version update to the relay.

Btw is there a way to determine what version of the relay a provider(such as hashio) is using? @Nana-EC did change this to the 0.12.0 milestone which hasn't yet been released so I can't confirm if it addresses my issue completely.

**Comment by Nana-EC** [comment]
Hi @mshakeg this is the PR - https://github.com/hashgraph/hedera-json-rpc-relay/pull/696

`0.12.0-rc1` has been in previewnet and testnet for a few days so you can verify it there.

You can do quick curls to relay deployments to check the version they're using
```
curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":"2","method":"web3_clientVersion","params":[]}' <endpoint
```
e.g. `curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":"2","method":"web3_clientVersion","params":[]}' https://testnet.hashio.io/api`

We're hoping to eventually have an improved UI for the live page `<relay_endpoint>/openrpc` that serves up the open rpc schema doc to display the current version e.g https://testnet.hashio.io/openrpc

Hope that helps

**Comment by mshakeg** [comment]
Hi @Nana-EC thanks for this.

Hi @Ivo-Yankov strangely enough this is still an issue. I deployed a contract with the `getNotLotsOfData` function in the initial post's example and it fails on all count > 126 and succeeds on all counts <= 126. I've attached the curl for you to test:
```
curl 'https://testnet.hashio.io/api' \
  -H 'authority: testnet.hashio.io' \
  -H 'accept: */*' \
  -H 'cache-control: max-age=0' \
  -H 'content-type: application/json' \
  --data-raw '{"method":"eth_call","params":[{"gas":"0x4c4b40","to":"0x0000000000000000000000000000000002eafdd2","data":"0x42787747000000000000000000000000000000000000000000000000000000000000007f"},"latest"],"id":1,"jsonrpc":"2.0"}' \
  --compressed
```
Change the `7f` at the very end of `params.data` to `7e` to change `count` from `127` to `126` and demonstrate that the latter succeeds whilst the former fails.

**Comment by mshakeg** [comment]
Hi @Nana-EC , just wanted to follow up on whether this issue should be reopened as it hasn't been resolved at least not entirely.

**Comment by Nana-EC** [comment]
@mshakeg we'll confirm and reopen if SDK version 2.18.6 didn't not resolve this as expected.

**Comment by Ivo-Yankov** [comment]
Hi @mshakeg , I can confirm that the issue still seems to be present. I will get back to you once I've investigated it further.

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov great, thanks!

**Comment by Ivo-Yankov** [comment]
Hi @mshakeg, can you please check if the issue is still present with the latest versions of local-node, sdk, etc.? Although I was able to reproduce it earlier, now I only receive an `INSUFFICIENT_GAS` error for larger responses.

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov , I'm still getting back the same response from the hashio testnet relay, not `INSUFFICIENT_GAS`:
```
{"jsonrpc":"2.0","id":44,"error":{"code":-32603,"name":"Internal error","message":"[Request ID: 3c29d5d3-7903-4366-b5d5-e9f298038608] Error invoking RPC: "}}
```

Are you making the [same curl request](https://github.com/hashgraph/hedera-json-rpc-relay/issues/533?notification_referrer_id=NT_kwDOAmXRErM0NDMwMTUxMzM1OjQwMjI3MDkw#issuecomment-1325348832)?

**Comment by Ivo-Yankov** [comment]
Yes, but I was testing against a local node. I reproduced it on testnet and am currently debugging it

**Comment by mshakeg** [comment]
@Ivo-Yankov I see, I've noticed this as well with #765 , the local node performs much better than the hashio testnet relay

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov , have you managed to make progress on this issue?

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov , do you think like #765 there's a limit on the data, instead in this case not on the input but on the response size?

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov , just wanted to ask if any progress has been made on this issue, it's been almost 4 months since I created it.

**Comment by stoqnkpL** [comment]
Hi @mshakeg,

Thank you for surfacing this issue. I'm sorry for not getting back to you sooner. We're looking into the problem. 

We executed the queries against a local consensus node (with `ContractCallLocal` gRPC queries, bypassing the relay), and were successful in getting larger results, as long as the gas limit provided was high enough. (The gas limit used by the curl requests you provided appears to be high enough, so this shouldn't be the root cause of the issue).

Our guess as to what is happening under the hood when you receive the internal error is that the consensus node returns a status `INSUFFICIENT_TX_FEE` for the query when larger amounts of data are being returned as a result. 

Before executing a query, the relay executes a query COST request, which is supposed to return information about the cost of execution for the query, then the relay tries to execute the query providing this cost as a fee. For some reason, it appears the query COST request does not return a high enough value for the transaction fee when the resulting bytes have a larger size.

We'll dig deeper and try to provide a definitive resolution for this issue as soon as possible. It appears to only be a problem when using the testnet relay and not reproducible with local-node.

**Comment by mshakeg** [comment]
Hi @stoqnkpL thanks for the detailed reply. Could maybe overestimating the query cost fix the issue specifically x1.1 as indicated in the [JS SDK docs](https://hashgraph.github.io/hedera-sdk-js/classes/_contract_contractcallquery_.contractcallquery.html#getcost)?

**Comment by stoqnkpL** [comment]
> Hi @stoqnkpL thanks for the detailed reply. Could maybe overestimating the query cost fix the issue specifically x1.1 as indicated in the [JS SDK docs](https://hashgraph.github.io/hedera-sdk-js/classes/_contract_contractcallquery_.contractcallquery.html#getcost)?

ah yes, this seems to be related. We can try multiplying by 1.1
