### ISSUE TITLE
subgraph data source templating handlers not triggered

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#757]
### Description

#644 was originally created to address an issue with [subgraph data source templates](https://thegraph.com/docs/en/developing/creating-a-subgraph/#instantiating-a-data-source-template), however, the issue hasn't been resolved entirely due to a yet undetermined issue.

I've tested that the issue is on both:
1. the latest local-node(v2.3.2) which uses the create1 address for contract addresses and on
2. the latest hashio testnet relay(v0.13.0) which uses the hedera account/entity id for contract addresses

The local-node behaviour is actually worse than hashio as not even normal data source events are being indexed.

### Steps to reproduce

(I) To demo issue on local-node:
1. Checkout to the branch in [this pr](https://github.com/mshakeg/hedera-json-rpc-relay/pull/4)
2. In `hardhat-example` project root start latest local node: `npm run hedera-start`
3. Run the script `test:hgf` to deploy the `GreeterFactory` and create 2 contracts using both `create1` and `create2` opcodes and to call methods on each contract that emit an event.
4. Once local-node has started start up `graph-node` by running the `docker compose up` on the `docker-compose.yml` command in the `subgraph-example` project root.
5. create and deploy subgraph to local graph-node
6. Observe that absolutely NO `----------- in` logs are shown in the graph-node container's logs

(II) To demo issue on testnet:
1. (similar to (I)2.) Run the script `test:hgf:testnet` to deploy the `GreeterFactory` and create 2 contracts to testnet
2. start up `graph-node` pointing to hashio's testnet relay by running the `docker compose up` on the `docker-compose.testnet.yml` in the `subgraph-example` project root.
3. Observe that ONLY the greeter create1 and create2 logs(`----------- in handleGreeter1Created` and `----------- in handleGreeter2Created`) are shown in the graph-node container's logs, however the data source template logs(`in handleGreetingSet`) on the create1 and create2 Greeter contracts DO NOT show up.

(III) To demo that the graph node indexes the subgraph 100% against the hardhat node:
1. In `hardhat-example` project root start hardhat local node: `npm run hardhat-start`
2. Run the script `test:hgf:hardhat_local`.
3. Once local-node has started start up `graph-node` by running the `docker compose up` on the `docker-compose.hardhat.yml` in the `subgraph-example` project root.
4. create and deploy subgraph to local graph-node
5. Observe that ALL logs are shown in the graph-node container's logs as expected
```
// in the handleGreeter1Created event handler:
ERRO ----------- in handleGreeter1Created

// in the handleGreeter2Created event handler:
ERRO ----------- in handleGreeter2Created

// in the handleGreetingSet event handler for Greeter with create1 address:
ERRO --------- in handleGreetingSet
ERRO bound greeterContract
ERRO greetingValue hello from greeter1

// in the handleGreetingSet event handler for Greeter with create2 address:
ERRO --------- in handleGreetingSet
ERRO bound greeterContract
ERRO greetingValue hello from greeter2
```

### Hedera network

testnet

### Version

relay@0.13.0 & local-node@2.3.2

### Operating system

macOS

**Comment by dimitrovmaksim** [comment]
For create 2 addresses, there were still place where the mirror node would return the long-zero address instead of the alias address. For example `api/v1/contracts/{contractId}/results/logs` and `api/v1/contracts/results/logs` would return the alias address for the logs addresses, but `api/v1/contracts/results/{transactionIdOrHash}` would return the long-zero address in the logs. Also eth_getLogs could not filter logs by multiple addresses, which affected the graph (fix is merged). I'm waiting for all fixes and PRs to be merged and released so I can finish the updated example and add all notes to the readme.

**Comment by mshakeg** [comment]
@dimitrovmaksim I see, thanks, I'll keep this issue open until I've confirmed that everything works as expected.

**Comment by bmino** [comment]
Hey! I believe @dimitrovmaksim has described the issue as I see it but here is some data to contribute should further investigation be open. All data is against testnet.

1) Factory contract is created @ 0.0.49092539 (`0x0000000000000000000000000000000002ed17bb`)
2) Factory creates Greeter via create2 @ 0.0.49092555
  a) Hashed address: `0x6004ce29ac9124b565d9c5736458c882d30618da`
  b) Mapped address: `0x0000000000000000000000000000000002ed17cb`
3) Greeter emits GreetingSet(string) event
  a) Query performed to get block timestamps: https://testnet.mirrornode.hedera.com/api/v1/blocks/0x5770ee85053f5a0f957b8b272fe011412d394b5334a00b92d765131137bb7972da5f25d3f794e5a989a16cfff2843547
  b) Query performed to get contract calls: https://testnet.mirrornode.hedera.com/api/v1/contracts/results?timestamp=gte:1671056786.036255003&timestamp=lte:1671056787.949538062
  c) Query performed to get event logs from the calls in (3b): https://testnet.mirrornode.hedera.com/api/v1/contracts/0x6004ce29ac9124b565d9c5736458c882d30618da/results/1671056787.517382003

Notice that the logs parameter from 3c uses the mapping address instead of the hashed address. This value represents the address of the contract that emitted the event since any transaction can call other contracts internally that emit the same event signature. I believe the graph-node discards these logs because the address (mapped address) does not match the address it is subscribed to (hashed address).

**Comment by bmino** [comment]
Tried pointing an example subgraph against the current `main` branch of the relayer (commit hash a3062db26a795daf76b1d75acb7ee0a49f551ea8) but am still seeing the same behavior.

Here is the simplified subgraph I'm using to sandbox with:
<https://github.com/pangolindex/subgraph-templated>

**Comment by bmino** [comment]
thanks for the reply @dimitrovmaksim. were these changes not included in the https://github.com/hashgraph/hedera-mirror-node/releases/tag/v0.70.0 release? looks like PRs 4942 and 4943 address it

**Comment by mshakeg** [comment]
Hey @dimitrovmaksim , just wanted to ask which issue tracks that fix, I don't see any for the [mirror node 0.71.0 milestone](https://github.com/hashgraph/hedera-mirror-node/milestone/126).

Also does hashio's json rpc point to the `mirrornode.hedera.com` mirror node?

**Comment by dimitrovmaksim** [comment]
This one, it's resolved already https://github.com/hashgraph/hedera-mirror-node/issues/5005

**Comment by mshakeg** [comment]
@dimitrovmaksim does that include the fix to return the evm address(instead of the long zero account address) in the transaction receipt or only for contract logs/results?

**Comment by dimitrovmaksim** [comment]
`/contracts/results/{transactionIdorHash}` endpoint is the equivalent of the transaction receipt

**Comment by mshakeg** [comment]
@dimitrovmaksim oh yes, my bad

**Comment by mshakeg** [comment]
[mirror-node#4364](https://github.com/hashgraph/hedera-mirror-node/issues/4364) is a blocking issue of this issue on testnet at least.

**Comment by Kalina-Todorova** [comment]
Hi @mshakeg although the epic is not marked complete, this endpoint should be available both on testnet and mainnet. Could you please verify on your end?

**Comment by mshakeg** [comment]
Hi @Kalina-Todorova , which endpoint are you referring to?

`/api/v1/contracts/results/{txHash}` doesn't work on `https://testnet.mirrornode.hedera.com`, hence why [txs can't be searched by txHash on hashscan's testnet env](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/348)

**Comment by dimitrovmaksim** [comment]
I think the issue is with hashscan this is what i get when trying search for a transaction 
<img width="1783" alt="Screenshot 2023-01-04 at 14 48 53" src="https://user-images.githubusercontent.com/20456492/210558726-631d7c77-ca28-4bed-9a11-d00bebde715e.png">

and the testnet mirror node returns it correctly https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x8d8fc48db70f07c9d1d4426739bf88371ad22fae73f233494f94ed1bb17fbfea

**Comment by mshakeg** [comment]
Hi @dimitrovmaksim are there maybe 2 kinds of txHashes on Hedera i.e. a 48 byte and a 32 byte(like Ethereum) hash? The 32 byte one doesn't seem to have an issue as you demonstrated, however the 48 byte one does, for example using the 48 byte `Transaction Hash` listed on hashscan for the following tx:
```
https://hashscan.io/testnet/transaction/1672246158.253213546?tid=0.0.29667223-1672246145-152791237
```
fails with a 400 Bad Request:
```
https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x5d5dd074e80852c3ffd47571a162fc5fe93135360b45d178bf7b68e88bdebec7fd2d2929e11cb3c12b35b7746ec8f16b
```

**Comment by dimitrovmaksim** [comment]
I think at the start the mirror node did not truncate the hash to 32 bytes. I'm not sure how the transaction hash is generated exactly but it's larger than 32bytes and is being then truncated to the first 32 bytes.

**Comment by mshakeg** [comment]
Hi @dimitrovmaksim you are correct about the truncation, truncating my above example 48 byte tx hash works:
```
https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x5d5dd074e80852c3ffd47571a162fc5fe93135360b45d178bf7b68e88bdebec7
```

**Comment by dimitrovmaksim** [comment]
And another thing, there are 2 types of hashes the hex one and a base64(i think), and not all transaction types can be queried from the `contract/results/{tx}` endpoint. I think it returns only `ETHEREUMTRANSACTION` and `CONTRACTCALL` (maybe there are 1 or 2 more types)

**Comment by mshakeg** [comment]
@dimitrovmaksim I've done a very basic investigation I don't think this issue would be resolved as the **long zero account id address** is still returned in the `logs` array instead of the **evm_address**.

IIRC the graph node makes an `eth_getBlockByNumber` and then for each txHash in `result.transactions` make an `eth_getTransactionReceipt` to get that tx's logs to index.

I got block 28_840_298(_28 Dec 2022, 16:19 UTC_) and then on the only tx (`0x69b247bd0d702b0eba56755a0508af98e22f48bdd0baf88a1aac984354248869 `) in it I made an `eth_getTransactionReceipt` request:
```
curl 'https://testnet.hashio.io/api' \
  -H 'authority: testnet.hashio.io' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: max-age=0' \
  -H 'content-type: application/json' \
  -H 'origin: https://web3-rpc-debug.vercel.app' \
  -H 'referer: https://web3-rpc-debug.vercel.app/' \
  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
  --data-raw '{"method":"eth_getTransactionReceipt","params":["0x69b247bd0d702b0eba56755a0508af98e22f48bdd0baf88a1aac984354248869"],"id":44,"jsonrpc":"2.0"}' \
  --compressed
```
which returns the following response:
```json
{
  "result": {
    "blockHash": "0x064ae62cb68a225fa95d6173dd436fc88e46b1e502226752be80797f46027d65",
    "blockNumber": "0x1b8116a",
    "from": "0x0000000000000000000000000000000001c4af97",
    "to": "0x0000000000000000000000000000000002ecfab5",
    "cumulativeGasUsed": "0x186a00",
    "gasUsed": "0x186a00",
    "contractAddress": "0x0000000000000000000000000000000002ecfab5",
    "logs": [
      {
        "address": "0x0000000000000000000000000000000002ecf9c1",
        "blockHash": "0x064ae62cb68a225fa95d6173dd436fc88e46b1e502226752be80797f46027d65",
        "blockNumber": "0x1b8116a",
        "data": "0x000000000000000000000000000000000000000000000000000000000022bd530000000000000000000000000000000000000000000000000000000002ecf8b700000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000001e7a40000000000000000000000000000000000000002cb9a0dee4ad120fcc6e5963e9000000000000000000000000000000000000000000000000000000007f1a78aa00000000000000000000000000000000000000000000000000000000000128ee",
        "logIndex": "0x0",
        "removed": false,
        "topics": [
          "0x3af44aa39b24bd726eb8f514761a6cb917e8b4e0e07cebd5bd54d4107eff6936",
          "0x0000000000000000000000000000000000000000000000000000000002ecfab5",
          "0x0000000000000000000000000000000000000000000000000000000001c4af97"
        ],
        "transactionHash": "0x69b247bd0d702b0eba56755a0508af98e22f48bdd0baf88a1aac984354248869",
        "transactionIndex": "0x1"
      }
    ],
    "logsBloom": "0x00000000000000000000080000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000200000000000000000000000000100000040000000000000000000000000000000000000000000000000040000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000400000000000000",
    "transactionHash": "0x69b247bd0d702b0eba56755a0508af98e22f48bdd0baf88a1aac984354248869",
    "transactionIndex": "0x1",
    "effectiveGasPrice": "0x0",
    "status": "0x1"
  },
  "jsonrpc": "2.0",
  "id": 44
}
```
Note that the `address` field in the first and only log object is `0x0000000000000000000000000000000002ecf9c1` which is a long zero account address, whereas the evm_address for the contract is in fact the create2 address: `0x01a57c79dd3a77a9bdfa1101925fa7a2c0d61629`

**Comment by mshakeg** [comment]
@dimitrovmaksim as I see, any idea when the testnet mirror node will be updated to 0.71.0?

**Comment by dimitrovmaksim** [comment]
Sorry I don't have this kind of info

**Comment by Kalina-Todorova** [comment]
Hi @mshakeg, mirror-node version on testnet is now 0.71.0 so you can test out against is now. Feel free to reopen is you face further issues.
